---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nnfproco/vidacafe.nnf-pro.com
    - cd assets/images/
    - mkdir avatar gallery menu
    - cp $DEPLOYPATH/assets/images/* assets/images/
    - cp * $DEPLOYPATH
