---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nnfproco/vidacafe.nnf-pro.com

    - /bin cp $DEPLOYPATH/assets/images/* assets/images/

    - /bin cp * $DEPLOYPATH

    - cd /home/nnfproco/vidacafe.nnf-pro.com/assets/images/

    - mkdir avatar gallery menu
